// Code generated by tygo. DO NOT EDIT.

//////////
// source: article.go

export interface Article {
  id: string;
  pubDate: string;
  pubEpoch: number /* int64 */;
  title: string;
  description: string;
  content: string;
  url: string;
  read: boolean;
  parent: string;
  icon: string;
}

//////////
// source: subscription.go

export interface Subscription {
  id: string;
  title: string;
  description: string;
  url: string;
  lastUpdated: string;
  'channel>muted': boolean;
  'channel>icon': string;
  articles: Article[];
}

//////////
// source: user.go

export interface User {
  id: string;
  subscriptions: Subscription[];
  readingList: Article[];
  lastUpdated: string;
}
