// Code generated by tygo. DO NOT EDIT.

//////////
// source: handler.go

export interface UserEvent {
  id: string;
}
export interface SubscriptionEvent {
  id: string;
  title: string;
  url: string;
  userId: string;
}

//////////
// source: server.go

export interface Server {
  DB?: any /* gocb.Bucket */;
  Router?: any /* mux.Router */;
}
