// Code generated by tygo. DO NOT EDIT.

//////////
// source: article.go

export interface Article {
  id: string;
  pubDate: string;
  pubEpoch: number /* int64 */;
  title: string;
  description: string;
  content: string;
  url: string;
  read: boolean;
  parent: string;
  icon: string;
}

//////////
// source: events.go

export interface UserEvent {
  id: string;
}
export interface SubscriptionEvent {
  id: string[];
  title: string;
  url: string;
  userId: string;
}
export interface ArticleEvent {
  url: string;
  userId: string;
}

//////////
// source: subscription.go

export interface Subscription {
  id: string;
  title: string;
  description: string;
  url: string;
  lastUpdated: string;
  muted: boolean;
  icon: string;
  articles: Article[];
}

//////////
// source: user.go

export interface User {
  id: string;
  subscriptions: string[];
  readingList: string[];
  lastUpdated: string;
}
