// Code generated by tygo. DO NOT EDIT.

//////////
// source: events.go

export interface UserEvent {
  id: string;
}
export interface SubscriptionEvent {
  id?: string;
  title?: string;
  url?: string;
  userId?: string;
}
export interface ArticleEvent {
  id?: string;
  url?: string;
  userId?: string;
  parent?: string;
}

//////////
// source: server.go

export interface Server {
  DB?: any /* gocb.Bucket */;
  Router?: any /* mux.Router */;
}
export type Handler = any;
