// Code generated by tygo. DO NOT EDIT.

//////////
// source: server.go

export interface Server {
  DB?: any /* sql.DB */;
  Router?: any /* mux.Router */;
}
export interface UserEvent {
  id: string;
}
export interface SubscriptionEvent {
  title: string;
  url: string;
}
